[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adds a new check for jokers that unlock new jokers by turning into others, such as Alert -> Legacy, or The Batter -> Off Switch

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if _c.rarity and _c.rarity == 4 and specific_vars and not specific_vars.not_hidden then "
position = "before"
match_indent = true
payload = '''
if _c.paperback_secret_unlock and _c.paperback_secret_unlock == true and _c.unlocked then
  localize{type = 'unlocks', key = 'paperback_upgrade_unlock', set = 'Other', nodes = desc_nodes, vars = loc_vars}
else
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "elseif hide_desc then"
position = 'before'
match_indent = true
payload = '''
end
'''
